import React from "react";
import { useNavigate } from "react-router-dom";
import { Box, Typography, Button, Container } from "@mui/material";

const Home = () => {
  const navigate = useNavigate();

  return (
    <Container sx={{ marginTop: 4 }}>
      <Box sx={{ textAlign: "center", marginBottom: 4 }}>
        {/* Welcome Message */}
        <Typography variant="h4" sx={{ fontWeight: "bold", marginBottom: 2 }}>
          Welcome to Newsletter Generated By AI!
        </Typography>
        <Typography variant="body1" sx={{ marginBottom: 4 }}>
          Get AI-generated newsletters tailored just for you. Click the button below to get started.
        </Typography>

        {/* Button to navigate to the Newsletter page */}
        <Button
          variant="contained"
          color="primary"
          onClick={() => navigate("/newsletter")}
          sx={{ paddingY: 1.5, fontWeight: "bold" }}
        >
          Go to Newsletter
        </Button>
      </Box>
    </Container>
  );
};

export default Home;
